#!/bin/bash
# author: drampil@
# edited by: keruvinb@

help_function() {
day=$(date +%A)

if [[ $day == "Sunday" ]]
then
        echo "Will F., Jose, and Ellie"
elif [[ $day == "Monday" ]]
then
        echo "Will F. and Ellie"
elif [[ $day == "Tuesday" ]]
then
        echo "Garrett and Christopher"
elif [[ $day == "Wednesday" ]]
then
        echo "Corey, Jacob, and Rabia"
elif [[ $day == "Thursday" ]]
then
        echo "Jose, Marc, and Ajeet"
elif [[ $day == "Friday" ]]
then
        echo "Shawntel and Jacob"
elif [[ $day == "Saturday" ]]
then
        echo "Shawntel, Rabia, and Marc"
else
        echo "error"
fi
}

triage_function() {
day=$(date +%A)

if [[ $day == "Sunday" ]]
then
        echo "Will F, Ellie, and Jose"
elif [[ $day == "Monday" ]]
then
        echo "Ajeet, Shams, amd Jose"
elif [[ $day == "Tuesday" ]]
then
        echo "Shams, Jacob, and Shawntel"
elif [[ $day == "Wednesday" ]]
then
        echo "Garrett, Rabia, and Christopher"
elif [[ $day == "Thursday" ]]
then
        echo "Corey and Will F."
elif [[ $day == "Friday" ]]
then
        echo "Christopher, and Marc"
elif [[ $day == "Saturday" ]]
then
        echo "Shawntel, Rabia, and Corey"
else
        echo "error"
fi
}

weather_function(){
curl -s https://darksky.net/forecast/38.9379,-77.3624/us12/en | grep -w "summary swap\|low\|high" | sed 's/&nbsp;//g' | sed s'/<[^>]*>//g' | sed 's/^ *//g';
}

echo "Morning Report"
date +%A
date +"%dth %B, %Y"
echo
echo "Weather"
weather_function
echo
echo "Assigned to Help room"
help_function
echo

#Help channel output
echo "Assigned to Triage"
triage_function
echo
